sudo: false

language: php

php:
  - 5.5
  - 5.6
  - hhvm

services:
  - mysql

env:
  - DB=mysql

mysql:
  database: skills-app
  username: root
  encoding: utf8

before_script:
  - mysql -e 'create database `skills-app`;'
  

script:
  - composer install
  - php artisan migrate:install
  - php artisan migrate
  - php artisan migrate:status
  - mysql -e 'RENAME TABLE `skills-app`.`category_product` TO `skills-app`.`category_products`;'
  - php artisan migrate --seed
  - mysql -e 'RENAME TABLE `skills-app`.`category_products` TO `skills-app`.`category_product`;'
  
  - vendor/bin/codecept run acceptance

notifications:
  email: false