sudo: required

language: php

php:
  - 5.6
  - hhvm

services:
  - mysql

env:
  - DB=mysql

mysql:
  database: bottlestore-app
  username: root
  encoding: utf8

before_script:
  - mysql -e 'create database `bottlestore-app`;'
  

script:
  - composer install
  - php artisan migrate:install
  - php artisan migrate
  - php artisan migrate:status
  - php artisan migrate --seed
  
  - vendor/bin/codecept run acceptance

notifications:
  email: false