sudo: required

language: php

php:
  - 5.6
  - hhvm

services:
  - mysql

env:
  - DB=mysql

  before_script:
  - mysql -e 'create database skills-app;'
script:
  - composer install
  - vendor/bin/codecept run acceptance

notifications:
  email: false