sudo: required

language: php

php:
  - 5.6
  - hhvm

services:
  - mysql

env:
  - DB=mysql

mysql:
  database: skills-app
  username: root
  encoding: utf8

script:
  - composer install
  - vendor/bin/codecept run acceptance

notifications:
  email: false