sudo: required

language: php

php:
  - 5.6
  - hhvm

services:
  - mysql

env:
  - DB=mysql

mysql:
  database: skills-app
  username: root
  encoding: utf8

before_script:
  - mysql -e 'create database `skills-app`;'


script:
  - composer install
  - php artisan migrate --force
  - vendor/bin/codecept run acceptance

notifications:
  email: false